### ISSUE TITLE
Accessory out of compliance 

### ISSUE THREAD

**Issue by Paradoxpm** [hamkichi/homebridge-echonet-lite-eolia#2]
Unable to add homebridge when plugin is active. Home app complains about "Accessory out of compliance".
Errors in log:

**Logs:**

[30/9/2021, 14:05:55] [homebridge-echonet-lite-eolia] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
[30/9/2021, 14:05:55] [homebridge-echonet-lite-eolia] Error: 
    at CoolingThresholdTemperature.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at CoolingThresholdTemperature.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1891:14)
    at CoolingThresholdTemperature.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1456:24)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:62)
[30/9/2021, 14:05:55] [homebridge-echonet-lite-eolia] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
[30/9/2021, 14:05:55] [homebridge-echonet-lite-eolia] Error: 
    at CoolingThresholdTemperature.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at CoolingThresholdTemperature.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1891:14)
    at CoolingThresholdTemperature.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1456:24)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:62)
[30/9/2021, 14:05:55] [homebridge-echonet-lite-eolia] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
[30/9/2021, 14:05:55] [homebridge-echonet-lite-eolia] Error: 
    at CoolingThresholdTemperature.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at CoolingThresholdTemperature.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1891:14)
    at CoolingThresholdTemperature.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1456:24)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:62)
[30/9/2021, 14:05:55] [homebridge-echonet-lite-eolia] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
[30/9/2021, 14:05:55] [homebridge-echonet-lite-eolia] Error: 
    at HeatingThresholdTemperature.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at HeatingThresholdTemperature.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1891:14)
    at HeatingThresholdTemperature.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1456:24)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:62)
[30/9/2021, 14:05:55] [homebridge-echonet-lite-eolia] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
[30/9/2021, 14:05:55] [homebridge-echonet-lite-eolia] Error: 
    at HeatingThresholdTemperature.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at HeatingThresholdTemperature.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1891:14)
    at HeatingThresholdTemperature.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1456:24)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:62)
[30/9/2021, 14:05:55] [homebridge-echonet-lite-eolia] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
[30/9/2021, 14:05:55] [homebridge-echonet-lite-eolia] Error: 
    at HeatingThresholdTemperature.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at HeatingThresholdTemperature.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1891:14)
    at HeatingThresholdTemperature.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1456:24)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:62)

**Comment by hamkichi** [comment]
Thank you for opening the issue!

Please provide further information to investigate. 

--------------
#### Model number of the AC you want to control

#### Steps to reproduce the issue
1.  xxxxx
2. yyyyy
3. zzzzz

#### What's the expected result?
-

#### What's the actual result?
-

#### Homebrige log (make sure to enable debug mode and include all logs.  if you have many of logs, you can attach as a file)

#### Additional details / screenshot (optional)

**Comment by Paradoxpm** [comment]
Model number:
CS-X289C

- Steps to reproduce the issue:

1. Install the plugin & reboot Homebridge.
2. Open Home app on iPhone
3. Add Homebridge. No air conditioners found, error as in previous log.

- What's the expected result?

No errors in log.
Accessories show in Home app.

- What's the actual result?

No air conditioners shown in Home app. Errors in log.

- Log:
- [3/10/2021, 19:06:02] [HB Supervisor] Starting Homebridge with extra flags: -I -D
[3/10/2021, 19:06:02] [HB Supervisor] Started Homebridge v1.3.4 with PID: *
Initializing HAP-NodeJS v0.9.4...
[3/10/2021, 19:06:03] Loaded config.json with 1 accessories and 1 platforms.
[3/10/2021, 19:06:04] Loaded 0 cached accessories from cachedAccessories.
[3/10/2021, 19:06:04] ---
[3/10/2021, 19:06:05] Loaded plugin: homebridge-config-ui-x@4.41.2
[3/10/2021, 19:06:05] Registering platform 'homebridge-config-ui-x.config'
[3/10/2021, 19:06:05] ---
[3/10/2021, 19:06:05] Loaded plugin: homebridge-echonet-lite-eolia@0.2.1
[3/10/2021, 19:06:05] Registering platform 'homebridge-echonet-lite-eolia.EoliaPlatform'
[3/10/2021, 19:06:06] [Config] Initializing config platform...
[3/10/2021, 19:06:06] [Config] Running in Service Mode
[3/10/2021, 19:06:06] [EoliaPlatform] Initializing EoliaPlatform platform...
[3/10/2021, 19:06:06] [EoliaPlatform] Finished initializing platform: EoliaPlatform
[3/10/2021, 19:06:06] [EoliaPlatform] Executed didFinishLaunching callback
[3/10/2021, 19:06:06] [EoliaPlatform] finish launching version:0.1.0
Preparing Advertiser for '*NAME*' using ciao backend!
Setup Payload:
*NUMBER*
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ *number* │     
    └────────────┘     
                       
Starting to advertise '*NAME*' using ciao backend!
[3/10/2021, 19:06:06] Homebridge v1.3.4 (*NAME*) is running on port *.
[3/10/2021, 19:06:06] [EoliaPlatform] Adding new accessory: *IP*
[3/10/2021, 19:06:06] [EoliaPlatform] Adding new accessory: *IP*
[3/10/2021, 19:06:06] [EoliaPlatform] Adding new accessory: *IP*
[3/10/2021, 19:06:06] [EoliaPlatform] Adding new accessory: *IP*
[3/10/2021, 19:06:07] [EoliaPlatform] Triggered GET Active
[3/10/2021, 19:06:07] [EoliaPlatform] Triggered GET CurrentHeaterCoolerState
[3/10/2021, 19:06:07] [EoliaPlatform] Triggered GET Active
[3/10/2021, 19:06:07] [EoliaPlatform] Triggered GET TargetHeaterCoolerState
[3/10/2021, 19:06:07] [EoliaPlatform] Triggered GET CurrentTemperature
[3/10/2021, 19:06:07] [EoliaPlatform] Triggered GET CoolingThresholdTemperature
[3/10/2021, 19:06:07] [EoliaPlatform] Triggered GET HeatingThresholdTemperature
[3/10/2021, 19:06:07] [EoliaPlatform] Triggered GET Active
[3/10/2021, 19:06:07] [EoliaPlatform] Triggered GET CurrentHeaterCoolerState
[3/10/2021, 19:06:07] [EoliaPlatform] Triggered GET Active
[3/10/2021, 19:06:07] [EoliaPlatform] Triggered GET TargetHeaterCoolerState
[3/10/2021, 19:06:07] [EoliaPlatform] Triggered GET CurrentTemperature
[3/10/2021, 19:06:07] [EoliaPlatform] Triggered GET CoolingThresholdTemperature
[3/10/2021, 19:06:07] [EoliaPlatform] Triggered GET HeatingThresholdTemperature
[3/10/2021, 19:06:07] [EoliaPlatform] Triggered GET Active
[3/10/2021, 19:06:07] [EoliaPlatform] Triggered GET CurrentHeaterCoolerState
[3/10/2021, 19:06:07] [EoliaPlatform] Triggered GET Active
[3/10/2021, 19:06:07] [EoliaPlatform] Triggered GET TargetHeaterCoolerState
[3/10/2021, 19:06:07] [EoliaPlatform] Triggered GET CurrentTemperature
[3/10/2021, 19:06:07] [EoliaPlatform] Triggered GET CoolingThresholdTemperature
[3/10/2021, 19:06:07] [EoliaPlatform] Triggered GET HeatingThresholdTemperature
[3/10/2021, 19:06:07] [EoliaPlatform] Triggered GET Active
[3/10/2021, 19:06:07] [EoliaPlatform] Triggered GET CurrentHeaterCoolerState
[3/10/2021, 19:06:07] [EoliaPlatform] Triggered GET Active
[3/10/2021, 19:06:07] [EoliaPlatform] Triggered GET TargetHeaterCoolerState
[3/10/2021, 19:06:07] [EoliaPlatform] Triggered GET CurrentTemperature
[3/10/2021, 19:06:07] [EoliaPlatform] Triggered GET CoolingThresholdTemperature
[3/10/2021, 19:06:07] [EoliaPlatform] Triggered GET HeatingThresholdTemperature
[3/10/2021, 19:06:08] [homebridge-echonet-lite-eolia] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
[3/10/2021, 19:06:08] [homebridge-echonet-lite-eolia] Error: 
    at CoolingThresholdTemperature.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at CoolingThresholdTemperature.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1891:14)
    at CoolingThresholdTemperature.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1456:24)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:62)
[3/10/2021, 19:06:08] [homebridge-echonet-lite-eolia] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
[3/10/2021, 19:06:08] [homebridge-echonet-lite-eolia] Error: 
    at HeatingThresholdTemperature.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at HeatingThresholdTemperature.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1891:14)
    at HeatingThresholdTemperature.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1456:24)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:62)

**Comment by Paradoxpm** [comment]
This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.

**Comment by hamkichi** [comment]
According to the log, the plugin seems to discover 4 devices.  Please let me know details of these devices:
(You own 4 CS-X289C ACs, All IPs are same, etc.)
```
[3/10/2021, 19:06:06] [EoliaPlatform] Adding new accessory: IP
[3/10/2021, 19:06:06] [EoliaPlatform] Adding new accessory: IP
[3/10/2021, 19:06:06] [EoliaPlatform] Adding new accessory: IP
[3/10/2021, 19:06:06] [EoliaPlatform] Adding new accessory: IP
```


Also, please open `http://<your homebridge ip>:8581/accessories` and check if AC devices are displayed and able to control.

**Comment by Paradoxpm** [comment]
Now that you mention it, I have 5 devices, but only 4 are detected (those detected have the correct IP address). The fifth is detected and works in the Eolia app but is not detected by this plugin. 
The devices are:
CS-X569C2-W
CS-X289C-W
CS-EX229C-W　x2
CS-X229C-W

**Comment by hamkichi** [comment]
If you can see your ACs in homebridge web ui and not in the Home app, you should re-check hombridge and Home app configuration.  AFAIK homebridge plugins don't do anything about homebridge-Homekit integration.

Home app will show devices and "no response" even if characteristic is null.  I don't think the error causes the issue.

Anyway, I will add logic to return default value to handle null value and extend discovery time to detect more ACs.
